name: Build and Test on iPhone 12 Pro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          scheme: "Yelp Search"
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -project "Yelp Search/Yelp Search.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 12 Pro"
      - name: Test
        env:
          scheme: "Yelp Search"
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild test-without-building -scheme "$scheme" -project "Yelp Search/Yelp Search.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 12 Pro"
